### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by EZTEQ**
Because reasons.

### CODE REVIEW

**Comment by squarerootfury** [comment]
Won't fix. This **r**epository is for legacy purposes only.

**Comment by waldyrious** [comment]
Since this repo has been restored as the primary source for the website, I think it makes sense to reopen and merge this PR.

**Comment by cmllr** [comment]
I don't think I want to merge this.

**Comment by waldyrious** [comment]
@cmllr would you mind explaining why? True, it's not really a typo, but it's a justifiable change IMHO -- after all, in English common nouns are only capitalized if there's a specific reason to do.

**Comment by cmllr** [comment]
This text passage was removed yesterday.

**Comment by waldyrious** [comment]
Understood -- I missed that detail.

**Pull request closed without merging**
