### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by christianmalek**

### CODE REVIEW

**Comment by squarerootfury** [comment]
This repo is deprecated. The new repo is/ will be https://github.com/squarerootfury/ldc.js

**Comment by cmllr** [comment]
Well, I think I have to overthink my current repository stragegy.

I think it would be the best to reanimate this repo soon. So you don't have to add an deprecation notice, but thanks for the suggestion!

**Comment by waldyrious** [comment]
Ok. I'll keep an eye on both repos and will start contributing once it's clear which codebase is (and will continue to be) the current one.

**Comment by waldyrious** [comment]
Since this repo has been restored as the primary source for the website, I think it makes sense to reopen and merge this PR. What do you think, @cmllr?

**Comment by cmllr** [comment]
The official name changed from "Linux Distribution Chooser" to "Distrochooser", which fits better to the domain. That's the reason why this PR won't get merged.

**Comment by waldyrious** [comment]
Would you agree to a PR incorporating the rest of the changes, then?

**Comment by cmllr** [comment]
The situation here is quite similar to https://github.com/cmllr/distrochooser/pull/39, the passages were removed/ the contents are different now.

**Comment by waldyrious** [comment]
Ah, right, then. Sorry for the noise.

**Comment by cmllr** [comment]
All good, discussion is always okay :)

**Pull request closed without merging**
